[package]
name = "aoc-2019-09a"
version = "0.1.0"
authors = ["Mikael Auno <mikael.auno@viaplay.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
